name = "garanti_javascript"
version = "0.1.0"
description = "Garanti test-runner for the JavaScript target."
licences = ["Apache-2.0"]

target = "javascript"

[repository]
type = "github"
user = "eliasson"
repo = "garanti"

[dependencies]
garanti =  { path = "../garanti" }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
logging = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
