name = "garanti"
version = "0.1.0"
description = "Garanti is a Gleam test framework built around suites, parallel execution, and readable failure messages."
licences = ["Apache-2.0"]

[repository]
type = "github"
user = "eliasson"
repo = "garanti"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
